### ISSUE TITLE
Select DNS Record type for multiple entries.

### ISSUE THREAD

**Issue by cupcakearmy** [cupcakearmy/docker-ddns-cloudflare#2]
> There was never an error in the logs, it just didn't update. The reason was that the call to get the list of records for the domain returned more than one for my domain. That's why I added "Type=A" in my pull request. I haven't reviewed the code in the rewritten version to see if it limited the number of records returned.

**Comment by cupcakearmy** [comment]
I've updated the image to only select a type records. is it fixed? @digitalcraig

**Comment by digitalcraig** [comment]
Unfortunately, I won't be able to test for some time. My IP address only changes if I'm offline for several hours such as the power outage I had. I will let you know if there are any other issues. Thanks for looking into it.

**Comment by cupcakearmy** [comment]
Ok I'll close it then for now. Feel free to open again if there are issues :)
